
version: '3'

services:
    drupal:
        image: drupal
        ports:
            - '8080:80'
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
        depends_on:
            - postgres
    postgres:
        image: postgres
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
