
version: '3.1'

services:

    drupal:
      build: .
      ports:
          - "80:80"
      volumes:
          - drupal-modules:/var/www/html/modules
          - drupal-profiles:/var/www/html/profiles
          - drupal-sites:/var/www/html/sites
          - ./themes:/var/www/html/themes

    postgres:
        environment:
            - POSTGRES_DB_FILE=/run/secrets/postgres_db
            - POSTGRES_USER_FILE=/run/secrets/postgres_user
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        secrets:
            - postgres_db
            - postgres_user
            - postgres_password
        volumes:
            - drupal-data:/var/lib/postgresql/data

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    drupal-data:

secrets:
  postgres_db:
    file: postgres_db.txt
  postgres_user:
    file: postgres_user.txt
  postgres_password:
    file: postgres_password.txt